name: Deploy on web

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy index.html to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ec2-100-27-41-217.compute-1.amazonaws.com
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "index.html"
          target: "/var/www/html/"
